version: "3"
services:
  frontend:
    build:
      context: frontend
      target: development
    image: reaskgres-frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
